ci: only restart pm2 on deploying

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -47,9 +47,9 @@ jobs:
       runs-on: [self-hosted, Server-19]
       needs: test
       steps:
-         - name: Delete previous deployment
-           shell: bash
-           run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."
+         #  - name: Delete previous deployment
+         #    shell: bash
+         #    run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."
 
          - name: Checkout code
            uses: actions/checkout@v4
@@ -76,16 +76,16 @@ jobs:
 
          - name: Restart PM2 process
            shell: bash
-           run: pm2 start ecosystem.config.cjs
+           run: pm2 restart ecosystem.config.cjs
 
    deploy-server-51:
       name: Deploy to server 51
       runs-on: [self-hosted, Server-51]
       needs: test
       steps:
-         - name: Delete previous deployment
-           shell: bash
-           run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."
+         #  - name: Delete previous deployment
+         #    shell: bash
+         #    run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."
 
          - name: Checkout code
            uses: actions/checkout@v4
@@ -112,4 +112,4 @@ jobs:
 
          - name: Restart PM2 process
            shell: bash
-           run: pm2 start ecosystem.config.cjs
+           run: pm2 restart ecosystem.config.cjs
