ci: add new deployment for server 5.1

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -40,8 +40,9 @@ jobs:
          - name: Unit testing
            run: npm run test
 
-   deploy:
-      runs-on: self-hosted
+   deploy-server-19:
+      name: Deploy to server 19
+      runs-on: [self-hosted, Server-19]
       needs: test
       steps:
          - name: Delete previous deployment
@@ -54,7 +55,45 @@ jobs:
          - name: Load environment variables
            shell: bash
            run: |
-              echo "${{ secrets.ENV_VARIABLE }}" > .env.production
+              echo "${{ secrets.ENV_VARIABLE_SVR19 }}" > .env.production
+              ls
+
+         - name: Set up Node.js
+           uses: actions/setup-node@v4
+           with:
+              node-version: '20.x'
+              cache: npm
+
+         - name: Install dependencies
+           run: npm ci
+
+         - name: Generate PWA assets
+           run: npm run generate-pwa-assets
+
+         - name: Build the React app
+           shell: bash
+           run: npm run build
+
+         - name: Restart PM2 process
+           shell: bash
+           run: pm2 start ecosystem.config.cjs
+
+   deploy-server-51:
+      name: Deploy to server 51
+      runs-on: [self-hosted, Server-51]
+      needs: test
+      steps:
+         - name: Delete previous deployment
+           shell: bash
+           run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."
+
+         - name: Checkout code
+           uses: actions/checkout@v4
+
+         - name: Load environment variables
+           shell: bash
+           run: |
+              echo "${{ secrets.ENV_VARIABLE_SVR51 }}" > .env.production
               ls
 
          - name: Set up Node.js
