ci: update deployement config

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -24,6 +24,7 @@ jobs:
 
    test:
       runs-on: ubuntu-latest
+      needs: sonarcloud
       steps:
          - name: Checkout code
            uses: actions/checkout@v4
@@ -44,9 +45,9 @@ jobs:
       runs-on: self-hosted
       needs: test
       steps:
-         - name: Delete previous PM2 process if exists
+         - name: Delete previous deployment
            shell: bash
-           run: pm2 delete "${{ secrets.APP_NAME }}" || echo "Process not found. Skipping deletion."
+           run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."
 
          - name: Checkout code
            uses: actions/checkout@v4
@@ -75,4 +76,4 @@ jobs:
 
          - name: Restart PM2 process
            shell: bash
-           run: pm2 serve ./dist --name "${{ secrets.APP_NAME }}" --port ${{ secrets.PORT }} --spa
+           run: pm2 start ecosystem.config.cjs
